### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (undeploy-DU)

### ISSUE THREAD

**Issue by FarhanAhmad** [RestComm/jain-slee.msrp#1]
Hi, mvn clean install produces following error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (undeploy-DU) on project restcomm-slee-ra-msrp-DU: Execution undeploy-DU of goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run failed: Plugin org.apache.maven.plugins:maven-antrun-plugin:1.7 or one of its dependencies could not be resolved: Failed to collect dependencies at org.apache.maven.plugins:maven-antrun-plugin:jar:1.7 -> org.apache.maven:maven-plugin-api:jar:2.0.11: Failed to read artifact descriptor for org.apache.maven:maven-plugin-api:jar:2.0.11: Could not transfer artifact org.apache.maven:maven-plugin-api:pom:2.0.11 from/to central (https://repo.maven.apache.org/maven2): Received fatal alert: protocol_version -> [Help 1]

**Comment by FarhanAhmad** [comment]
putting the plugins of resources/msrp/du/pom.xml inside pluginmanagment tag resolves the error.

**Comment by tuijldert** [comment]
Hi,

So why am I not hindered by this in my builds?
I'm no `maven` expert but according documentation `<pluginManagement>` is something for parent pom's (which this 1 clearly isn't).

Furthermore, your problem is not the `antrun-plugin` but the `plugin-api` according the error dump.

Can you elaborate please?

Thanks,
Tom.
